site_name: Blazam Documentation
site_description: Documentation for the Blazam application
site_author: Chris Jacobsen
copyright: Blazam 2024
repo_url: https://github.com/Blazam-App/BLAZAM
edit_uri: https://github.com/Blazam-App/docs.blazam.org/blob/master/docsource
docs_dir: docsource
site_dir: docs
extra:
  analytics:
    provider: google
    property: G-TG0YV4T565
theme:
  features:
    - content.action.edit
    - navigation.footer
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  #- pymdownx.superfences
  #- pymdownx.inlinehilite
  #- pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
    - Home: 'index.md'
    - Installation Guide:
        - Web Installer: 'install/web.md'
        - Manual Installation: 'install/manual.md'
        - Configuration: 'install/config.md'
        - Security: 'install/security.md'
        - Updating:
          - 'Manual Updates': 'update/manual.md'
          - 'Self Updates': 'update/self.md'
          - 'Auto Updates': 'update/auto.md'
    - Admin Guide:
      - First Run: 'admin/initialSetup.md'
      - Settings:
        - Application: 'admin/settings/application.md'
      - Permissions: 'admin/permissions.md'
      - Templates: 'admin/templates.md'
      - Fields: 'admin/fields.md'
  
    - About:
        - 'License': 'license.md'
        - 'Privacy': 'privacy.md'