# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
      # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Deploy MkDocs
        # You may pin to the exact commit or the version.
        # uses: mhausenblas/mkdocs-deploy-gh-pages@d77dd03172e96abbcdb081d8c948224762033653
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
     
      - name: Configure git credentials
  # You may pin to the exact commit or the version.
  # uses: OleksiyRudenko/gha-git-credentials@ac5b66bcf3873df4259c681d957d8c145980171f
        uses: OleksiyRudenko/gha-git-credentials@v2.1.1
        with:
          # Configure global git user name, email, password (default: false)
          #global: # optional, default is false
          # <git-user-email@domain.com> (default: github-action@users.noreply.github.com)
          #email: # optional, default is github-action@users.noreply.github.com
          # Git User Name (default: "GitHub Action")
          #name: # optional, default is GitHub Action
          # GitHub Actor Username (default: github.actor)
          #actor: # optional, default is GITHUB_ACTOR
          # GitHub Token
          token: '${{ secrets.SECRET_KEY }}'
          
      - name: Commit Changes
      
        run: |
         #git config --global user.email "you@example.com"
         #git config --global user.name "Github"
          git add .
          git commit -m "Build files"
          git push origin live
